### ISSUE TITLE
「検査陽性者の状況」の追加

### ISSUE THREAD

**Issue by yoshiosakamoto** [Code-for-Fukuoka/covid19#15]
## 改善詳細 / Details of Improvement
- 福岡市のオープンデータに「軽症・中等症」や「重症」といった情報がないため、東京都の最初のタイルである「検査陽性者の状況」をコメントアウトしている。
- 表示レイアウトを変更し、このまとめの情報を提供するようにしたい。

**Comment by tokunaga33** [comment]
福岡市含め関係者と協議した結果、「軽症・中等症」や「重症」のパネルは残したまま、人数を -人のように表記することとしました。非公表のため内訳はないという意味を含めて、その旨注記も追加します。※「死亡」についても同様です
本日リリース済みのためクローズします
