### ISSUE TITLE
Linuxでno such file or directory: 'install'と言われる件のヒントの記載について，リンクが正しく張れていない。

### ISSUE THREAD

**Issue by kuwayamamasayuki** [Code-for-Fukuoka/covid19#20]
## 起こっている問題 / The Problem
- Linuxでno such file or directory: 'install'と言われる件のヒントの記載について，リンクが正しく張れていない。

## スクリーンショット / Screenshot

![誤表示](https://user-images.githubusercontent.com/4161113/76739279-56b71c00-67af-11ea-863d-f1d96c7a6115.png)

## 期待する見せ方・挙動 / Expected Behavior

![正表示](https://user-images.githubusercontent.com/4161113/76739338-66cefb80-67af-11ea-92ac-fee8ab905f95.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by tokunaga33** [comment]
ありがとうございます。
こちら対応してもらったようなのでクローズします
