### ISSUE TITLE
福岡市オープンデータの内容とポータルサイトに表示されるデータが異なる

### ISSUE THREAD

**Issue by kumanoryo** [Code-for-Fukuoka/covid19#31]
## 起こっている問題 / The Problem
- 2020-3-18 10:13 (UTC+09:00) に更新された [福岡市　新型コロナウイルス感染症　陽性患者発表情報](https://ckan.open-governmentdata.org/dataset/401307_covid19_patients) の情報とポータルサイトに表示される陽性患者のデータが異なる。（反映されていない）

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/7764581/76933167-d9ff7b80-692f-11ea-80a6-5e5284f03db3.png)

## 期待する見せ方・挙動 / Expected Behavior
![image](https://user-images.githubusercontent.com/7764581/76933127-c94f0580-692f-11ea-8492-f4666a259cc2.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. ポータルサイトを表示する。

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by tokunaga33** [comment]
自動取り込みはまだ実装されておらず、夕方以降1日1回のデータ反映を行なっています。
今後自動取り込みは対応していきたいとは思っております。
お気づきありがとうございます
