### ISSUE TITLE
data.jsonの自動更新

### ISSUE THREAD

**Issue by kawax** [Code-for-Fukuoka/covid19#36]
## 改善詳細 / Details of Improvement
- data.jsonをGitHub Actionで自動更新（PRまで）

## 期待する見せ方・挙動 / Expected behavior
- https://github.com/Code-for-Fukuoka/data_setup があるので自動化は簡単。
- すでに作ったのでしばらく試して問題なさそうならPRします。https://github.com/kawax/covid19-fukuoka

## 決めて欲しいこと
- 実行時間：1日1回なら何時にするか。1時間ごとに実行すると更新されてないのに時間だけ変更される。
- PR先ブランチ：現在は`development`にする予定（正確にはデフォルトのブランチ）。いきなりmasterはやめたほうがいいけどdevelopmentからmasterへのマージが必要になる。

現状の想定
- `data/development`ブランチ（固定）で更新、`development`にPR、を1時間ごと。
- 固定ブランチなら1時間ごとに実行してもPRは一つ、同じPRが更新される。
- 変更箇所を見て不要ならマージせずそのまま、更新されてたらマージして`data/development`は削除。
- 次の実行時に新しいPRが作られるので繰り返し。
- 本番環境に反映させるには`development`から`master`へのPRを作る。

**Comment by tokunaga33** [comment]
ありがとうございます！反応が遅れて申し訳ありません。
現在の環境ですが、本番環境はNetlifyではなく別のサーバでの提供となっています。
そのため本番環境への自動化は現在サーバでのcron処理等で実装しかかっております。
ただし、GitHub上のdata.jsonの更新は自動化には含めておらず、developmentによるステージング環境の反映をどうしようかと検討中です。
作成しただいたGitActionsでの方法も欲しかったので、こちら含めて検討したいと思います！
大変助かります〜、ほんとありがとうございます。

**Comment by kawax** [comment]
data_setupが変わってたので本番環境上で直接更新してるんですかね。
一応PRで確認を挟んだほうがいいとは思いますけど。
元データが変わって壊れることはよくある。

**Comment by tokunaga33** [comment]
ありがとうございます！
「検査陽性者の状況」の対応を入れたため、data_setup更新しています。
プルリク残した方がわかりやすいですよね・・・
今後なるべくそうしたいと思います
