### ISSUE TITLE
グラフの表示期間指定機能

### ISSUE THREAD

**Issue by yoshiosakamoto** [Code-for-Fukuoka/covid19#53]
## 改善詳細 / Details of Improvement
棒グラフが小さくなってきたので、福岡県と同じようなグラフの表示期間指定機能を追加したい。

## 期待する見せ方・挙動 / Expected behavior
・初期表示時の期間は２ヵ月とする。（福岡県と同様）
・「表示期間を指定する」スイッチはデフォルトONにする。（福岡県はOFF）

**Comment by yoshiosakamoto** [comment]
@NM502i 
@uttnaoki 
福岡県の追加されているソースを持ってきてテスト環境に適用してみましたが、
うまく動きませんでした。
できれば、福岡市の棒グラフにも表示期間のコントロールを入れて頂けると大変助かります。

**Comment by NM502i** [comment]
@yoshiosakamoto 
各グラフに表示期間の指定機能を追加してdevelopmentにcommitしときました。

**Comment by yoshiosakamoto** [comment]
@NM502i 
ありがとうございました！
本番環境に反映しました。
